; Tests for cancellation-aware coroutines (llvm.coro.cancelled marker).
;
; Frame layout of a cancellation-aware coroutine (as generated by clang):
;   [0] resume fn ptr, [ptrsize] destroy fn ptr, [2*ptrsize] cancellation flag
;   (i8), then the promise (aligned), then the suspend index and spills.
; The flag is located at the fixed offset 2 * ptrsize — no promise-type
; information is needed, so request_cancel/cancel_requested work through any
; coroutine_handle<Promise> handle, including handles whose template argument
; is a base class of the real promise type.
;
; Non-cancellation-aware coroutines keep the exact frame layout of today:
; the promise follows the two function pointers directly (the flag is only
; reserved for coroutines that opted in).
;
; A cancellation-aware coroutine (as generated by clang):
;   - initializes the flag to false in the ramp function (frontend-generated),
;   - checks the flag at every suspension-point resumption block (the
;     `*.ready` blocks, before await_resume) via `llvm.coro.cancel_requested`
;     and branches to the cancellation entry block when set,
;   - the cancellation entry block is marked with llvm.coro.cancelled (used by
;     CoroFrame to reserve the flag; the marker is removed after splitting),
;   - `llvm.coro.request.cancel` / `llvm.coro.cancel.requested` are lowered by
;     CoroEarly into plain pointer arithmetic at the fixed offset (the offset
;     knowledge lives in CoroEarly only),
;   - in the destroy/cleanup clones the resumption blocks are reachable only
;     through a condition that is constant-false (destroy never resumes), so
;     instcombine folds it and the checks plus the cancellation entry block
;     are removed; destroying a cancelled coroutine runs the normal destroy
;     path.
; RUN: opt < %s -passes='module(coro-early),cgscc(coro-split),instcombine,simplifycfg' -S | FileCheck %s

%struct.promise = type { i64 }

declare void @print(i32)
declare void @unhandled_cancellation()

define ptr @f() presplitcoroutine {
entry:
  %promise = alloca %struct.promise, align 8
  %id = call token @llvm.coro.id(i32 0, ptr %promise, ptr @f, ptr null)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr null)
  call void @print(i32 0)
  ; The frontend initializes the cancellation flag to false after the promise
  ; construction, before the coroutine can be suspended. The flag lives at
  ; the fixed offset 2 * ptrsize (frame + 16 on a 64-bit target).
  %flag.init.ptr = getelementptr i8, ptr %hdl, i64 16
  store i8 0, ptr %flag.init.ptr, align 1
  br label %init

init:
  %initial_suspend = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %initial_suspend, label %init_suspend [i8 0, label %body
                                                   i8 1, label %init_suspend]

init_suspend:
  ret ptr %hdl

body:
  call void @print(i32 1)
  %suspend_result = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %suspend_result, label %suspend [i8 0, label %resume
                                             i8 1, label %suspend]

; Every suspension-point resumption block starts with the cancellation check
; (before await_resume): llvm.coro.cancel.requested reads the flag at frame +
; 16 (lowered by CoroEarly to a load + icmp) and branches to the cancellation
; entry block when set.
resume:
  %flag.cond = call i1 @llvm.coro.cancel.requested(ptr %hdl)
  br i1 %flag.cond, label %cancel.entry, label %resume.cont

resume.cont:
  call void @print(i32 2)
  br label %final

final:
  %final_suspend = call i8 @llvm.coro.suspend(token none, i1 true)
  switch i8 %final_suspend, label %suspend [i8 0, label %resume.final
                                            i8 1, label %suspend]

resume.final:
  br label %suspend

; The cancellation entry block: marked with llvm.coro.cancelled, runs
; promise.unhandled_cancellation() and falls through to the final suspend.
cancel.entry:
  call void @llvm.coro.cancelled()
  call void @unhandled_cancellation()
  br label %final

suspend:
  call void @llvm.coro.end(ptr %hdl, i1 false, token none)
  ret ptr %hdl
}

; A coroutine without the cancellation marker must not gain any cancellation
; checks or extra frame fields: its promise follows the two function pointers
; directly, exactly as today.
define ptr @g() presplitcoroutine {
entry:
  %id = call token @llvm.coro.id(i32 0, ptr null, ptr @g, ptr null)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr null)
  br label %init

init:
  %initial_suspend = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %initial_suspend, label %init_suspend [i8 0, label %body
                                                   i8 1, label %init_suspend]

init_suspend:
  ret ptr %hdl

body:
  call void @print(i32 1)
  %suspend_result = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %suspend_result, label %suspend [i8 0, label %resume
                                             i8 1, label %suspend]

resume:
  br label %final

final:
  %final_suspend = call i8 @llvm.coro.suspend(token none, i1 true)
  switch i8 %final_suspend, label %suspend [i8 0, label %resume.final
                                            i8 1, label %suspend]

resume.final:
  br label %suspend

suspend:
  call void @llvm.coro.end(ptr %hdl, i1 false, token none)
  ret ptr %hdl
}

; CHECK-LABEL: define ptr @f(
; The ramp function initializes the cancellation flag to false.
; CHECK: call {{.*}}ptr @llvm.coro.begin
; CHECK: store i8 0, ptr %flag.init.ptr

; The non-cancellation-aware ramp function @g (printed right after @f) must
; not carry a cancellation flag.
; CHECK-LABEL: define ptr @g(
; CHECK-NOT: %flag.init.ptr
; CHECK-NOT: %flag.ptr

; The resume function keeps the suspension-point cancellation check. CoroEarly
; lowers llvm.coro.cancel.requested to a load from the fixed frame offset
; (i8 element GEP, so i64 16 means byte 16 — the offset 2 * ptrsize).
; CHECK-LABEL: define internal void @f.resume(
; CHECK: %flag.ptr = getelementptr inbounds {{(nuw )?}}i8, ptr %{{.*}}, i64 16
; CHECK: load i8, ptr %flag.ptr
; CHECK-NEXT: icmp {{ne|eq}} i8 %{{.*}}, 0
; CHECK-NEXT: br i1 %{{.*}}, label %{{cancel.entry|resume.cont}}, label %{{resume.cont|cancel.entry}}
; The cancellation entry block calls unhandled_cancellation and then reaches
; the final suspend.
; CHECK: call void @unhandled_cancellation()
; The marker is removed everywhere after splitting.
; CHECK-NOT: call void @llvm.coro.cancelled()

; Destroy and cleanup must NOT run unhandled_cancellation: the resumption
; blocks are only reachable through a constant-false condition there, which
; instcombine folds; the checks and the cancellation entry block are removed.
; CHECK-LABEL: define internal void @f.destroy(
; CHECK-NOT: %flag.ptr
; CHECK-NOT: unhandled_cancellation
; CHECK-NOT: llvm.coro.cancelled
; CHECK-LABEL: define internal void @f.cleanup(
; CHECK-NOT: %flag.ptr
; CHECK-NOT: unhandled_cancellation
; CHECK-NOT: llvm.coro.cancelled

; The non-cancellation-aware resume function gains no cancellation check.
; CHECK-LABEL: define internal void @g.resume(
; CHECK-NOT: %flag.ptr
; CHECK: load i{{[0-9]+}}, ptr %index.addr
; CHECK-NEXT: switch
