; Tests for coroutine cancellation with the always-present frame flag.
;
; Every coroutine with a promise carries a cancellation flag (i8) right after
; the promise object in its frame; LLVM's coroutine lowering always reserves
; it (for every promise-bearing coroutine) and does not care whether the
; frontend uses it:
;   - a cancellation-aware coroutine (as generated by clang when the promise
;     declares `unhandled_cancellation`) initializes the flag to false in the
;     ramp function and checks it at every suspension-point resumption block
;     (the `*.ready` blocks, before await_resume), branching to the
;     cancellation entry block when set,
;   - a promise-bearing coroutine without a cancellation handler never reads
;     the flag (the frame still reserves the byte, so a stray write from a
;     `request_cancel()` call does not go out of bounds — a lax
;     implementation of the language-level precondition, which requires the
;     coroutine to be cancellation-aware; calling `request_cancel()` on a
;     non-cancellation-aware coroutine is undefined behavior per
;     [coroutine.handle.cancel]),
;   - in the destroy/cleanup clones the resumption blocks are reachable only
;     through a condition that is constant-false (destroy never resumes), so
;     instcombine folds it and the checks plus the cancellation entry block
;     are removed; destroying a cancelled coroutine runs the normal destroy
;     path.
; RUN: opt < %s -passes='cgscc(coro-split),instcombine,simplifycfg' -S | FileCheck %s

%struct.promise = type { i64 }

declare void @print(i32)
declare void @unhandled_cancellation()

define ptr @f() presplitcoroutine {
entry:
  %promise = alloca %struct.promise, align 8
  %id = call token @llvm.coro.id(i32 0, ptr %promise, ptr @f, ptr null)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr null)
  call void @print(i32 0)
  ; The frontend initializes the cancellation flag to false after the promise
  ; construction, before the coroutine can be suspended. The flag lives right
  ; after the promise object (llvm.coro.promise + sizeof(promise)).
  %promise.ptr = call ptr @llvm.coro.promise(ptr %hdl, i32 8, i1 false)
  %flag.init.ptr = getelementptr i8, ptr %promise.ptr, i64 8
  store i8 0, ptr %flag.init.ptr, align 1
  br label %init

init:
  %initial_suspend = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %initial_suspend, label %init_suspend [i8 0, label %body
                                                   i8 1, label %init_suspend]

init_suspend:
  ret ptr %hdl

body:
  call void @print(i32 1)
  %suspend_result = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %suspend_result, label %suspend [i8 0, label %resume
                                             i8 1, label %suspend]

; Every suspension-point resumption block starts with the cancellation check
; (before await_resume): load the flag and branch to the cancellation entry
; block when set.
resume:
  %promise.ptr2 = call ptr @llvm.coro.promise(ptr %hdl, i32 8, i1 false)
  %flag.ptr = getelementptr i8, ptr %promise.ptr2, i64 8
  %flag = load i1, ptr %flag.ptr, align 1
  br i1 %flag, label %cancel.entry, label %resume.cont

resume.cont:
  call void @print(i32 2)
  br label %final

final:
  %final_suspend = call i8 @llvm.coro.suspend(token none, i1 true)
  switch i8 %final_suspend, label %suspend [i8 0, label %resume.final
                                            i8 1, label %suspend]

resume.final:
  br label %suspend

; The cancellation entry block: runs promise.unhandled_cancellation() and
; falls through to the final suspend.
cancel.entry:
  call void @unhandled_cancellation()
  br label %final

suspend:
  call void @llvm.coro.end(ptr %hdl, i1 false, token none)
  ret ptr %hdl
}

; A promise-bearing coroutine without a cancellation handler must not gain
; any cancellation checks (the frame still carries the flag byte; calling
; `request_cancel()` on it is undefined behavior per the library contract,
; though the reserved byte keeps an erroneous write in bounds).
define ptr @g() presplitcoroutine {
entry:
  %promise = alloca %struct.promise, align 8
  %id = call token @llvm.coro.id(i32 0, ptr %promise, ptr @g, ptr null)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr null)
  br label %init

init:
  %initial_suspend = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %initial_suspend, label %init_suspend [i8 0, label %body
                                                   i8 1, label %init_suspend]

init_suspend:
  ret ptr %hdl

body:
  call void @print(i32 1)
  %suspend_result = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %suspend_result, label %suspend [i8 0, label %resume
                                             i8 1, label %suspend]

resume:
  br label %final

final:
  %final_suspend = call i8 @llvm.coro.suspend(token none, i1 true)
  switch i8 %final_suspend, label %suspend [i8 0, label %resume.final
                                            i8 1, label %suspend]

resume.final:
  br label %suspend

suspend:
  call void @llvm.coro.end(ptr %hdl, i1 false, token none)
  ret ptr %hdl
}

; CHECK-LABEL: define ptr @f(
; The ramp function initializes the cancellation flag to false.
; CHECK: call {{.*}}ptr @llvm.coro.begin
; CHECK: store i8 0, ptr %flag.init.ptr

; The resume function keeps the suspension-point cancellation check.
; CHECK-LABEL: define internal void @f.resume(
; CHECK: call ptr @llvm.coro.promise
; CHECK: load i1, ptr %flag.ptr
; CHECK-NEXT: br i1 %{{.*}}, label %cancel.entry, label %resume.cont
; The cancellation entry block calls unhandled_cancellation and then reaches
; the final suspend.
; CHECK: call void @unhandled_cancellation()

; Destroy and cleanup must NOT run unhandled_cancellation: the resumption
; blocks are only reachable through a constant-false condition there, which
; instcombine folds; the checks and the cancellation entry block are removed.
; CHECK-LABEL: define internal void @f.destroy(
; CHECK-NOT: %flag.ptr
; CHECK-NOT: unhandled_cancellation
; CHECK-LABEL: define internal void @f.cleanup(
; CHECK-NOT: %flag.ptr
; CHECK-NOT: unhandled_cancellation

; The non-cancellation-aware resume function gains no cancellation check
; (no unhandled_cancellation handler exists), even though the frame carries
; the flag byte.
; CHECK-LABEL: define internal void @g.resume(
; CHECK-NOT: %flag.ptr
; CHECK-NOT: unhandled_cancellation
; CHECK: load i{{[0-9]+}}, ptr %index.addr
; CHECK-NEXT: switch
