; Tests for cancellation-aware coroutines (llvm.coro.cancelled marker).
;
; A cancellation-aware coroutine (as generated by clang):
;   - carries a cancellation flag (i8) in its frame, right after the promise,
;   - checks the flag at the beginning of the body and branches to the
;     cancellation entry block when set (this also keeps that block reachable),
;   - initializes the flag to false in the ramp function,
;   - checks the flag at the resume entry and branches to the cancellation
;     entry block (which runs `promise.unhandled_cancellation()`) when set,
;   - has its llvm.coro.cancelled marker removed after splitting.
; RUN: opt < %s -passes='cgscc(coro-split),simplifycfg' -S | FileCheck %s

%struct.promise = type { i64 }

declare void @print(i32)
declare void @unhandled_cancellation()

define ptr @f() presplitcoroutine {
entry:
  %promise = alloca %struct.promise, align 8
  %id = call token @llvm.coro.id(i32 0, ptr %promise, ptr @f, ptr null)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr null)
  call void @print(i32 0)
  br label %init

init:
  %initial_suspend = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %initial_suspend, label %init_suspend [i8 0, label %body
                                                   i8 1, label %init_suspend]

init_suspend:
  ret ptr %hdl

; The frontend emits a cancellation check right before the body. The flag
; lives right after the promise object (llvm.coro.promise + sizeof(promise)).
body:
  %promise.ptr = call ptr @llvm.coro.promise(ptr %hdl, i32 8, i1 false)
  %flag.ptr = getelementptr i8, ptr %promise.ptr, i64 8
  %flag = load i1, ptr %flag.ptr, align 1
  br i1 %flag, label %cancel.entry, label %body.cont

body.cont:
  call void @print(i32 1)
  %suspend_result = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %suspend_result, label %suspend [i8 0, label %resume
                                             i8 1, label %suspend]

resume:
  call void @print(i32 2)
  br label %final

final:
  %final_suspend = call i8 @llvm.coro.suspend(token none, i1 true)
  switch i8 %final_suspend, label %suspend [i8 0, label %resume.final
                                            i8 1, label %suspend]

resume.final:
  br label %suspend

; The cancellation entry block: marked with llvm.coro.cancelled, runs
; promise.unhandled_cancellation() and falls through to the final suspend.
cancel.entry:
  call void @llvm.coro.cancelled()
  call void @unhandled_cancellation()
  br label %final

suspend:
  call void @llvm.coro.end(ptr %hdl, i1 false, token none)
  ret ptr %hdl
}

; A coroutine without the cancellation marker must not gain any cancellation
; checks or extra frame fields.
define ptr @g() presplitcoroutine {
entry:
  %id = call token @llvm.coro.id(i32 0, ptr null, ptr @g, ptr null)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr null)
  br label %init

init:
  %initial_suspend = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %initial_suspend, label %init_suspend [i8 0, label %body
                                                   i8 1, label %init_suspend]

init_suspend:
  ret ptr %hdl

body:
  call void @print(i32 1)
  %suspend_result = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %suspend_result, label %suspend [i8 0, label %resume
                                             i8 1, label %suspend]

resume:
  br label %final

final:
  %final_suspend = call i8 @llvm.coro.suspend(token none, i1 true)
  switch i8 %final_suspend, label %suspend [i8 0, label %resume.final
                                            i8 1, label %suspend]

resume.final:
  br label %suspend

suspend:
  call void @llvm.coro.end(ptr %hdl, i1 false, token none)
  ret ptr %hdl
}

; CHECK-LABEL: define ptr @f(
; The ramp function initializes the cancellation flag to false.
; CHECK: call {{.*}}ptr @llvm.coro.begin
; CHECK: store i1 false, ptr %cancel.flag.addr

; The non-cancellation-aware ramp function @g (printed right after @f) must
; not carry a cancellation flag.
; CHECK-LABEL: define ptr @g(
; CHECK-NOT: cancel.flag

; The resume function checks the flag first and branches to the cancellation
; entry block (which runs unhandled_cancellation) when it is set.
; CHECK-LABEL: define internal void @f.resume(
; CHECK: load i1, ptr %cancel.flag.addr
; CHECK-NEXT: br i1 %{{.*}}, label %{{.*cancel.*}}, label %resume.switch
; The cancellation entry block calls unhandled_cancellation and then reaches
; the final suspend. (The block is printed before resume.switch.)
; CHECK: call void @unhandled_cancellation()
; CHECK: resume.switch:
; CHECK-NOT: call void @llvm.coro.cancelled()

; Destroy and cleanup must NOT run unhandled_cancellation: the cancellation
; check is removed, and the marker is gone everywhere.
; CHECK-LABEL: define internal void @f.destroy(
; CHECK-NOT: cancel.flag
; CHECK-NOT: unhandled_cancellation
; CHECK-NOT: call void @llvm.coro.cancelled()
; CHECK-LABEL: define internal void @f.cleanup(
; CHECK-NOT: cancel.flag
; CHECK-NOT: unhandled_cancellation
; CHECK-NOT: call void @llvm.coro.cancelled()

; The non-cancellation-aware resume function gains no cancellation check.
; CHECK-LABEL: define internal void @g.resume(
; CHECK-NOT: cancel.flag
; CHECK: load i{{[0-9]+}}, ptr %index.addr
; CHECK-NEXT: switch
